export const themes = [
  {
    id: 'midnight',
    name: 'Midnight',
    emoji: '🌙',
    description: 'Classic dark — easy on eyes',
    colors: {
      '--bg-primary':    '#0f172a',
      '--bg-secondary':  '#1e293b',
      '--bg-card':       '#1e293b',
      '--bg-hover':      '#334155',
      '--border':        '#334155',
      '--text-primary':  '#f1f5f9',
      '--text-secondary':'#94a3b8',
      '--accent':        '#6366f1',
      '--accent-hover':  '#4f46e5',
      '--accent-text':   '#ffffff',
      '--success':       '#22c55e',
      '--warning':       '#f59e0b',
      '--danger':        '#ef4444',
      '--sidebar-bg':    '#0f172a',
      '--sidebar-text':  '#94a3b8',
      '--sidebar-active':'#6366f1',
      '--button-primary':'#6366f1',
      '--kot-bg':        '#1e293b',
    }
  },
  {
    id: 'ocean',
    name: 'Ocean Blue',
    emoji: '🌊',
    description: 'Deep blue professional',
    colors: {
      '--bg-primary':    '#0c1a2e',
      '--bg-secondary':  '#112240',
      '--bg-card':       '#112240',
      '--bg-hover':      '#1d3461',
      '--border':        '#1d3461',
      '--text-primary':  '#e2f0fb',
      '--text-secondary':'#8ba6bf',
      '--accent':        '#0ea5e9',
      '--accent-hover':  '#0284c7',
      '--accent-text':   '#ffffff',
      '--success':       '#10b981',
      '--warning':       '#f59e0b',
      '--danger':        '#ef4444',
      '--sidebar-bg':    '#0c1a2e',
      '--sidebar-text':  '#8ba6bf',
      '--sidebar-active':'#0ea5e9',
      '--button-primary':'#0ea5e9',
      '--kot-bg':        '#112240',
    }
  },
  {
    id: 'forest',
    name: 'Forest',
    emoji: '🌿',
    description: 'Natural green calm',
    colors: {
      '--bg-primary':    '#0d1f17',
      '--bg-secondary':  '#132a1e',
      '--bg-card':       '#132a1e',
      '--bg-hover':      '#1a3d2b',
      '--border':        '#1a3d2b',
      '--text-primary':  '#dcf5e7',
      '--text-secondary':'#7dab8e',
      '--accent':        '#22c55e',
      '--accent-hover':  '#16a34a',
      '--accent-text':   '#ffffff',
      '--success':       '#22c55e',
      '--warning':       '#f59e0b',
      '--danger':        '#ef4444',
      '--sidebar-bg':    '#0d1f17',
      '--sidebar-text':  '#7dab8e',
      '--sidebar-active':'#22c55e',
      '--button-primary':'#22c55e',
      '--kot-bg':        '#132a1e',
    }
  },
  {
    id: 'sunset',
    name: 'Sunset',
    emoji: '🌅',
    description: 'Warm orange energy',
    colors: {
      '--bg-primary':    '#1a0f00',
      '--bg-secondary':  '#2d1a00',
      '--bg-card':       '#2d1a00',
      '--bg-hover':      '#3d2500',
      '--border':        '#3d2500',
      '--text-primary':  '#fff0e0',
      '--text-secondary':'#c49a6c',
      '--accent':        '#f97316',
      '--accent-hover':  '#ea6c0a',
      '--accent-text':   '#ffffff',
      '--success':       '#22c55e',
      '--warning':       '#f59e0b',
      '--danger':        '#ef4444',
      '--sidebar-bg':    '#1a0f00',
      '--sidebar-text':  '#c49a6c',
      '--sidebar-active':'#f97316',
      '--button-primary':'#f97316',
      '--kot-bg':        '#2d1a00',
    }
  },
  {
    id: 'royal',
    name: 'Royal Purple',
    emoji: '👑',
    description: 'Premium purple luxury',
    colors: {
      '--bg-primary':    '#120b1f',
      '--bg-secondary':  '#1e1035',
      '--bg-card':       '#1e1035',
      '--bg-hover':      '#2d1a4f',
      '--border':        '#2d1a4f',
      '--text-primary':  '#ede9fe',
      '--text-secondary':'#a78bda',
      '--accent':        '#a855f7',
      '--accent-hover':  '#9333ea',
      '--accent-text':   '#ffffff',
      '--success':       '#22c55e',
      '--warning':       '#f59e0b',
      '--danger':        '#ef4444',
      '--sidebar-bg':    '#120b1f',
      '--sidebar-text':  '#a78bda',
      '--sidebar-active':'#a855f7',
      '--button-primary':'#a855f7',
      '--kot-bg':        '#1e1035',
    }
  },
  {
    id: 'cherry',
    name: 'Cherry Red',
    emoji: '🍒',
    description: 'Bold red restaurant vibe',
    colors: {
      '--bg-primary':    '#1a0a0a',
      '--bg-secondary':  '#2d1010',
      '--bg-card':       '#2d1010',
      '--bg-hover':      '#3d1515',
      '--border':        '#3d1515',
      '--text-primary':  '#ffeaea',
      '--text-secondary':'#c47a7a',
      '--accent':        '#ef4444',
      '--accent-hover':  '#dc2626',
      '--accent-text':   '#ffffff',
      '--success':       '#22c55e',
      '--warning':       '#f59e0b',
      '--danger':        '#ef4444',
      '--sidebar-bg':    '#1a0a0a',
      '--sidebar-text':  '#c47a7a',
      '--sidebar-active':'#ef4444',
      '--button-primary':'#ef4444',
      '--kot-bg':        '#2d1010',
    }
  },
  {
    id: 'slate',
    name: 'Slate Gray',
    emoji: '🪨',
    description: 'Minimal corporate clean',
    colors: {
      '--bg-primary':    '#0f0f0f',
      '--bg-secondary':  '#1a1a1a',
      '--bg-card':       '#1a1a1a',
      '--bg-hover':      '#262626',
      '--border':        '#2a2a2a',
      '--text-primary':  '#e5e5e5',
      '--text-secondary':'#737373',
      '--accent':        '#525252',
      '--accent-hover':  '#404040',
      '--accent-text':   '#ffffff',
      '--success':       '#22c55e',
      '--warning':       '#f59e0b',
      '--danger':        '#ef4444',
      '--sidebar-bg':    '#0f0f0f',
      '--sidebar-text':  '#737373',
      '--sidebar-active':'#e5e5e5',
      '--button-primary':'#525252',
      '--kot-bg':        '#1a1a1a',
    }
  },
  {
    id: 'arctic',
    name: 'Arctic White',
    emoji: '🌨️',
    description: 'Clean light mode',
    colors: {
      '--bg-primary':    '#f8fafc',
      '--bg-secondary':  '#ffffff',
      '--bg-card':       '#ffffff',
      '--bg-hover':      '#f1f5f9',
      '--border':        '#e2e8f0',
      '--text-primary':  '#0f172a',
      '--text-secondary':'#64748b',
      '--accent':        '#0ea5e9',
      '--accent-hover':  '#0284c7',
      '--accent-text':   '#ffffff',
      '--success':       '#22c55e',
      '--warning':       '#f59e0b',
      '--danger':        '#ef4444',
      '--sidebar-bg':    '#0f172a',
      '--sidebar-text':  '#94a3b8',
      '--sidebar-active':'#0ea5e9',
      '--button-primary':'#0ea5e9',
      '--kot-bg':        '#f1f5f9',
    }
  },
  {
    id: 'gold',
    name: 'Gold Rush',
    emoji: '✨',
    description: 'Premium gold luxury',
    colors: {
      '--bg-primary':    '#0f0c00',
      '--bg-secondary':  '#1a1400',
      '--bg-card':       '#1a1400',
      '--bg-hover':      '#261e00',
      '--border':        '#2e2400',
      '--text-primary':  '#fff9e0',
      '--text-secondary':'#b8a050',
      '--accent':        '#f59e0b',
      '--accent-hover':  '#d97706',
      '--accent-text':   '#000000',
      '--success':       '#22c55e',
      '--warning':       '#f59e0b',
      '--danger':        '#ef4444',
      '--sidebar-bg':    '#0f0c00',
      '--sidebar-text':  '#b8a050',
      '--sidebar-active':'#f59e0b',
      '--button-primary':'#f59e0b',
      '--kot-bg':        '#1a1400',
    }
  },
  {
    id: 'rose',
    name: 'Rose Pink',
    emoji: '🌸',
    description: 'Soft modern pink',
    colors: {
      '--bg-primary':    '#1a0d12',
      '--bg-secondary':  '#2d1520',
      '--bg-card':       '#2d1520',
      '--bg-hover':      '#3d1d2b',
      '--border':        '#3d1d2b',
      '--text-primary':  '#fce7f3',
      '--text-secondary':'#c47a9a',
      '--accent':        '#ec4899',
      '--accent-hover':  '#db2777',
      '--accent-text':   '#ffffff',
      '--success':       '#22c55e',
      '--warning':       '#f59e0b',
      '--danger':        '#ef4444',
      '--sidebar-bg':    '#1a0d12',
      '--sidebar-text':  '#c47a9a',
      '--sidebar-active':'#ec4899',
      '--button-primary':'#ec4899',
      '--kot-bg':        '#2d1520',
    }
  },
];

export const DEFAULT_THEME = 'midnight';

export const getTheme = (id) => 
  themes.find(t => t.id === id) 
  || themes[0];
