/**
 * @fileoverview Master festival calendar for India (all states) and Australia.
 * Dates use dynamic computation for lunar/Hindu calendar approximations
 * and fixed Gregorian dates where applicable.
 */

/**
 * Returns YYYY-MM-DD string for a given year/month/day.
 */
function d(year, month, day) {
  return `${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
}

/**
 * Approximate lunar festival dates for 2024-2027.
 * Real production would use an astronomy library (ephem/hijri-js).
 * Dates are approximate ±1 day (official govt holidays).
 */
const LUNAR_DATES = {
  diwali:             { 2024: [2024,11,1],  2025: [2025,10,20], 2026: [2026,11,8],  2027: [2027,10,29] },
  holi:               { 2024: [2024,3,25],  2025: [2025,3,14],  2026: [2026,3,3],   2027: [2027,3,22]  },
  eid_ul_fitr:        { 2024: [2024,4,10],  2025: [2025,3,31],  2026: [2026,3,20],  2027: [2027,3,9]   },
  eid_ul_adha:        { 2024: [2024,6,17],  2025: [2025,6,7],   2026: [2026,5,27],  2027: [2027,5,17]  },
  muharram:           { 2024: [2024,7,7],   2025: [2025,6,26],  2026: [2026,6,16],  2027: [2027,6,5]   },
  milad_un_nabi:      { 2024: [2024,9,16],  2025: [2025,9,5],   2026: [2026,8,25],  2027: [2027,8,14]  },
  onam:               { 2024: [2024,9,15],  2025: [2025,9,5],   2026: [2026,8,25],  2027: [2027,9,13]  },
  ganesh_chaturthi:   { 2024: [2024,9,7],   2025: [2025,8,27],  2026: [2026,8,17],  2027: [2027,9,5]   },
  durga_puja:         { 2024: [2024,10,12], 2025: [2025,10,2],  2026: [2026,10,20], 2027: [2027,10,10] },
  navratri:           { 2024: [2024,10,3],  2025: [2025,9,22],  2026: [2026,10,11], 2027: [2027,10,1]  },
  navratri_chaitra:   { 2024: [2024,4,9],   2025: [2025,3,30],  2026: [2026,3,19],  2027: [2027,4,7]   },
  janmashtami:        { 2024: [2024,8,26],  2025: [2025,8,16],  2026: [2026,8,5],   2027: [2027,8,24]  },
  ram_navami:         { 2024: [2024,4,17],  2025: [2025,4,6],   2026: [2026,3,26],  2027: [2027,4,15]  },
  hanuman_jayanti:    { 2024: [2024,4,23],  2025: [2025,4,12],  2026: [2026,4,1],   2027: [2027,4,20]  },
  maha_shivratri:     { 2024: [2024,3,8],   2025: [2025,2,26],  2026: [2026,2,15],  2027: [2027,3,6]   },
  raksha_bandhan:     { 2024: [2024,8,19],  2025: [2025,8,9],   2026: [2026,7,29],  2027: [2027,8,17]  },
  guru_nanak_jayanti: { 2024: [2024,11,15], 2025: [2025,11,5],  2026: [2026,11,24], 2027: [2027,11,13] },
  buddha_purnima:     { 2024: [2024,5,23],  2025: [2025,5,12],  2026: [2026,5,31],  2027: [2027,5,21]  },
  chhath_puja:        { 2024: [2024,11,7],  2025: [2025,10,28], 2026: [2026,11,15], 2027: [2027,11,4]  },
  govardhan_puja:     { 2024: [2024,11,2],  2025: [2025,10,22], 2026: [2026,11,10], 2027: [2027,10,31] },
  bhai_dooj:          { 2024: [2024,11,3],  2025: [2025,10,23], 2026: [2026,11,11], 2027: [2027,11,1]  },
  karva_chauth:       { 2024: [2024,10,20], 2025: [2025,10,10], 2026: [2026,10,28], 2027: [2027,10,18] },
  teej:               { 2024: [2024,8,7],   2025: [2025,7,27],  2026: [2026,8,14],  2027: [2027,8,4]   },
  gudi_padwa:         { 2024: [2024,4,9],   2025: [2025,3,30],  2026: [2026,3,19],  2027: [2027,4,7]   },
  ugadi_exact:        { 2024: [2024,4,9],   2025: [2025,3,30],  2026: [2026,3,19],  2027: [2027,4,7]   },
  bihu_bohag:         { 2024: [2024,4,14],  2025: [2025,4,14],  2026: [2026,4,14],  2027: [2027,4,14]  },
  chinese_new_year:   { 2024: [2024,2,10],  2025: [2025,1,29],  2026: [2026,2,17],  2027: [2027,2,6]   },
  // Easter (approximate — Good Friday / Easter Sunday)
  easter:             { 2024: [2024,3,29],  2025: [2025,4,18],  2026: [2026,4,3],   2027: [2027,3,26]  },
};

function lunarDate(key, year) {
  const map = LUNAR_DATES[key];
  if (!map) return null;
  const arr = map[year] || map[Object.keys(map)[0]];
  return d(...arr);
}

function durationEnd(startStr, days) {
  const dt = new Date(startStr);
  dt.setDate(dt.getDate() + days);
  return dt.toISOString().slice(0,10);
}

/**
 * Generates the full festival calendar for a given year.
 * @param {number} year
 * @returns {Array<FestivalDef>}
 */
function generateCalendar(year) {
  const Y = year;

  const festivals = [
    // ─── NATIONAL HOLIDAYS (INDIA) ────────────────────────────────
    {
      key: 'republic_day',
      name: 'Republic Day 🇮🇳',
      country: 'IN',
      regions: ['all'],
      start: d(Y, 1, 26),
      end:   d(Y, 1, 26),
      special_mode: null,
      theme: {
        primary: '#FF9933', accent: '#138808', bg: '#001000',
        emoji: '🇮🇳', banner: 'Jai Hind! Happy Republic Day.',
        style: 'festive-tricolor',
      },
      menu_tags: ['sweets', 'snacks', 'beverages', 'mithai'],
      suggested_items: ['Tricolor Sandesh', 'Kheer', 'Samosa', 'Chai', 'Ladoo', 'Puri Sabzi'],
      offer_structure: { type: 'discount', label: 'Republic Day Special', value: 26, unit: 'percent', min_order: 200 },
      decor_tips: ['Tricolor bunting', 'National flag display', 'Saffron–white–green table runners'],
      category: 'national_holiday',
    },
    {
      key: 'independence_day',
      name: 'Independence Day 🇮🇳',
      country: 'IN',
      regions: ['all'],
      start: d(Y, 8, 15),
      end:   d(Y, 8, 15),
      special_mode: null,
      theme: {
        primary: '#FF9933', accent: '#138808', bg: '#001000',
        emoji: '🇮🇳', banner: 'Jai Hind! Happy Independence Day.',
        style: 'festive-tricolor',
      },
      menu_tags: ['sweets', 'snacks', 'street_food', 'beverages'],
      suggested_items: ['Pani Puri', 'Bhel Puri', 'Tricolor Halwa', 'Kesari Sharbat', 'Samosa', 'Matka Kulfi'],
      offer_structure: { type: 'discount', label: 'Independence Day Special', value: 15, unit: 'percent', min_order: 150 },
      decor_tips: ['National flag table flags', 'Tricolor balloons', 'Chakra motifs'],
      category: 'national_holiday',
    },
    {
      key: 'gandhi_jayanti',
      name: 'Gandhi Jayanti 🕊️',
      country: 'IN',
      regions: ['all'],
      start: d(Y, 10, 2),
      end:   d(Y, 10, 2),
      special_mode: null,
      theme: {
        primary: '#795548', accent: '#FFC107', bg: '#0a0500',
        emoji: '🕊️', banner: 'Tribute to the Father of the Nation.',
        style: 'festive-earthy',
      },
      menu_tags: ['vegetarian', 'satvik', 'sweets', 'khadi'],
      suggested_items: ['Goat Milk Sweets', 'Khichdi', 'Dal Baati', 'Fruit Platter', 'Simple Thali'],
      offer_structure: { type: 'discount', label: 'Gandhi Jayanti Satvik Thali', value: 10, unit: 'percent', min_order: 200 },
      decor_tips: ['Khadi cloth table runners', 'Charkha motif', 'White & beige décor'],
      category: 'national_holiday',
    },

    // ─── PAN-INDIA ────────────────────────────────────────────────
    {
      key: 'diwali',
      name: 'Diwali – Festival of Lights 🪔',
      country: 'IN',
      regions: ['all'],
      start: lunarDate('diwali', Y),
      end:   durationEnd(lunarDate('diwali', Y), 5),
      special_mode: null,
      theme: {
        primary: '#FF6B00', accent: '#FFD700', bg: '#1a0a00',
        emoji: '🪔', banner: 'Happy Diwali! Spread the light.',
        style: 'festive-orange',
      },
      menu_tags: ['sweets', 'mithai', 'namkeen', 'chai', 'paneer', 'dry_fruits'],
      suggested_items: ['Gulab Jamun', 'Kaju Katli', 'Rasgulla', 'Kheer', 'Chakli', 'Mixture', 'Masala Chai', 'Jalebi'],
      offer_structure: { type: 'combo', label: 'Diwali Mithai Box', value: 15, unit: 'percent', min_order: 500 },
      decor_tips: ['Diya string lights banner', 'Rangoli table mats', 'Gold & saffron table drapes'],
      category: 'pan_india',
    },
    {
      key: 'holi',
      name: 'Holi – Festival of Colours 🎨',
      country: 'IN',
      regions: ['all'],
      start: lunarDate('holi', Y),
      end:   durationEnd(lunarDate('holi', Y), 2),
      special_mode: null,
      theme: {
        primary: '#E91E63', accent: '#9C27B0', bg: '#1a001a',
        emoji: '🎨', banner: 'Bura na mano, Holi hai!',
        style: 'festive-pink',
      },
      menu_tags: ['thandai', 'gujiya', 'sweets', 'namkeen', 'beverages'],
      suggested_items: ['Thandai', 'Gujiya', 'Dahi Bhalla', 'Puran Poli', 'Namak Para', 'Malpua', 'Lassi'],
      offer_structure: { type: 'discount', label: 'Holi Special Platter', value: 20, unit: 'percent', min_order: 300 },
      decor_tips: ['Colourful streamers', 'Floral centrepieces', 'Rangoli at entrance'],
      category: 'pan_india',
    },
    {
      key: 'eid_ul_fitr',
      name: 'Eid ul-Fitr – Meethi Eid 🌙',
      country: 'IN',
      regions: ['all'],
      start: lunarDate('eid_ul_fitr', Y),
      end:   durationEnd(lunarDate('eid_ul_fitr', Y), 3),
      special_mode: null,
      theme: {
        primary: '#00897B', accent: '#FFD700', bg: '#001a15',
        emoji: '🌙', banner: 'Eid Mubarak! Khushiyan aur barkat mile.',
        style: 'festive-green',
      },
      menu_tags: ['biryani', 'kebab', 'haleem', 'sheer_khurma', 'non_veg'],
      suggested_items: ['Dum Biryani', 'Seekh Kebab', 'Haleem', 'Sheer Khurma', 'Firni', 'Mutton Rogan Josh', 'Phirni', 'Sewai'],
      offer_structure: { type: 'combo', label: 'Eid Dawat Special', value: 18, unit: 'percent', min_order: 600 },
      decor_tips: ['Crescent & star motifs', 'Green & gold drapes', 'Arabic lanterns'],
      category: 'pan_india',
    },
    {
      key: 'eid_ul_adha',
      name: 'Eid ul-Adha – Bakrid 🐑',
      country: 'IN',
      regions: ['all'],
      start: lunarDate('eid_ul_adha', Y),
      end:   durationEnd(lunarDate('eid_ul_adha', Y), 3),
      special_mode: null,
      theme: {
        primary: '#2E7D32', accent: '#FFD700', bg: '#001500',
        emoji: '🌙', banner: 'Eid ul-Adha Mubarak!',
        style: 'festive-green',
      },
      menu_tags: ['mutton', 'kebab', 'biryani', 'non_veg'],
      suggested_items: ['Mutton Biryani', 'Seekh Kebab', 'Nihari', 'Haleem', 'Mutton Korma', 'Sheer Khurma'],
      offer_structure: { type: 'discount', label: 'Bakrid Feast', value: 15, unit: 'percent', min_order: 500 },
      decor_tips: ['Islamic geometric patterns', 'Star & crescent', 'Gold & green banners'],
      category: 'pan_india',
    },
    {
      key: 'navratri',
      name: 'Navratri – Nine Nights 🪷',
      country: 'IN',
      regions: ['GJ', 'RJ', 'MP', 'MH', 'UP', 'HR', 'PB'],
      start: lunarDate('navratri', Y),
      end:   durationEnd(lunarDate('navratri', Y), 9),
      special_mode: 'satvik',
      theme: {
        primary: '#AB47BC', accent: '#FF8F00', bg: '#1a0020',
        emoji: '🪷', banner: 'Jai Mata Di! Navratri Greetings.',
        style: 'festive-purple',
      },
      menu_tags: ['vrat', 'satvik', 'no_onion_garlic', 'fasting'],
      suggested_items: ['Sabudana Khichdi', 'Kuttu Puri', 'Aloo Ki Subzi (no garlic)', 'Singhara Halwa', 'Makhana Kheer', 'Fruit Chaat', 'Rajgira Paratha'],
      offer_structure: { type: 'thali', label: 'Vrat Thali Special', value: 12, unit: 'percent', min_order: 200 },
      decor_tips: ['Marigold garlands', 'Red dupatta draping', 'Devi images at entrance'],
      category: 'regional',
    },
    {
      key: 'christmas',
      name: 'Christmas 🎄',
      country: 'IN',
      regions: ['all'],
      start: d(Y, 12, 20),
      end:   d(Y, 12, 26),
      special_mode: null,
      theme: {
        primary: '#C62828', accent: '#2E7D32', bg: '#001400',
        emoji: '🎄', banner: 'Merry Christmas & Happy New Year!',
        style: 'festive-red-green',
      },
      menu_tags: ['plum_cake', 'wine', 'roast', 'desserts', 'beverages'],
      suggested_items: ['Plum Cake', 'Gingerbread Cookies', 'Mulled Wine', 'Roast Chicken', 'Yule Log Cake', 'Hot Cocoa', 'Mince Pies'],
      offer_structure: { type: 'bundle', label: 'Christmas Feast Box', value: 20, unit: 'percent', min_order: 800 },
      decor_tips: ['Christmas tree', 'Santa hat table markers', 'Red & green table runners', 'Snowflake fairy lights'],
      category: 'pan_india',
    },

    // ─── MORE PAN-INDIA ───────────────────────────────────────────
    {
      key: 'makar_sankranti',
      name: 'Makar Sankranti – Kite Festival 🪁',
      country: 'IN',
      regions: ['all'],
      start: d(Y, 1, 14),
      end:   d(Y, 1, 15),
      special_mode: null,
      theme: {
        primary: '#F57F17', accent: '#1B5E20', bg: '#0a0500',
        emoji: '🪁', banner: 'Uttarayan Wishes! Til Gud Ghya, God God Bola.',
        style: 'festive-yellow',
      },
      menu_tags: ['til', 'jaggery', 'chikki', 'sweets', 'sesame'],
      suggested_items: ['Til Ladoo', 'Gajak', 'Peanut Chikki', 'Khichdi', 'Undhiyu (GJ)', 'Puran Poli', 'Revdi'],
      offer_structure: { type: 'combo', label: 'Sankranti Tilgul Box', value: 15, unit: 'percent', min_order: 200 },
      decor_tips: ['Kite-themed table décor', 'Yellow & orange bunting', 'Til & gur display jars'],
      category: 'pan_india',
    },
    {
      key: 'maha_shivratri',
      name: 'Maha Shivratri 🙏',
      country: 'IN',
      regions: ['all'],
      start: lunarDate('maha_shivratri', Y),
      end:   durationEnd(lunarDate('maha_shivratri', Y), 1),
      special_mode: 'satvik',
      theme: {
        primary: '#283593', accent: '#7B1FA2', bg: '#000010',
        emoji: '🙏', banner: 'Har Har Mahadev! Happy Maha Shivratri.',
        style: 'festive-purple',
      },
      menu_tags: ['vrat', 'satvik', 'fasting', 'no_onion_garlic', 'thandai'],
      suggested_items: ['Thandai', 'Sabudana Khichdi', 'Kuttu Pakora', 'Singhare Ki Puri', 'Makhana Kheer', 'Fruit Chaat'],
      offer_structure: { type: 'thali', label: 'Shivratri Vrat Thali', value: 12, unit: 'percent', min_order: 200 },
      decor_tips: ['Bilva patra motif', 'Blue & white', 'Shiva trishul table centerpiece'],
      category: 'pan_india',
    },
    {
      key: 'ram_navami',
      name: 'Ram Navami 🏹',
      country: 'IN',
      regions: ['all'],
      start: lunarDate('ram_navami', Y),
      end:   durationEnd(lunarDate('ram_navami', Y), 1),
      special_mode: 'satvik',
      theme: {
        primary: '#E65100', accent: '#FFD600', bg: '#1a0800',
        emoji: '🏹', banner: 'Jai Shri Ram! Happy Ram Navami.',
        style: 'festive-orange',
      },
      menu_tags: ['vrat', 'satvik', 'sweets', 'prasad'],
      suggested_items: ['Panjeeri', 'Panjiri Halwa', 'Gujiya', 'Panchakhadya', 'Fruits', 'Panchamrit'],
      offer_structure: { type: 'discount', label: 'Ram Navami Special', value: 10, unit: 'percent', min_order: 150 },
      decor_tips: ['Orange & yellow décor', 'Bow & arrow motifs', 'Marigold garlands'],
      category: 'pan_india',
    },
    {
      key: 'hanuman_jayanti',
      name: 'Hanuman Jayanti 🐒',
      country: 'IN',
      regions: ['all'],
      start: lunarDate('hanuman_jayanti', Y),
      end:   durationEnd(lunarDate('hanuman_jayanti', Y), 1),
      special_mode: 'satvik',
      theme: {
        primary: '#E65100', accent: '#FF6F00', bg: '#1a0500',
        emoji: '🐒', banner: 'Jai Bajrangbali! Happy Hanuman Jayanti.',
        style: 'festive-orange',
      },
      menu_tags: ['vrat', 'satvik', 'sweets', 'prasad', 'boondi'],
      suggested_items: ['Boondi Prasad', 'Besan Ladoo', 'Puri Sabzi', 'Halwa', 'Chola Puri'],
      offer_structure: { type: 'discount', label: 'Hanuman Jayanti Special', value: 10, unit: 'percent', min_order: 150 },
      decor_tips: ['Orange vermilion motifs', 'Saffron table runners', 'Diya display'],
      category: 'pan_india',
    },
    {
      key: 'raksha_bandhan',
      name: 'Raksha Bandhan 🪢',
      country: 'IN',
      regions: ['all'],
      start: lunarDate('raksha_bandhan', Y),
      end:   durationEnd(lunarDate('raksha_bandhan', Y), 1),
      special_mode: null,
      theme: {
        primary: '#E91E63', accent: '#FFD700', bg: '#1a0010',
        emoji: '🪢', banner: 'Happy Raksha Bandhan! Celebrate the bond.',
        style: 'festive-pink',
      },
      menu_tags: ['sweets', 'mithai', 'snacks', 'beverages', 'gifting'],
      suggested_items: ['Kaju Katli', 'Soan Papdi', 'Besan Ladoo', 'Rasgulla', 'Kalakand', 'Rose Sherbet', 'Pista Barfi'],
      offer_structure: { type: 'bundle', label: 'Rakhi Sweet Gift Box', value: 15, unit: 'percent', min_order: 300 },
      decor_tips: ['Colorful rakhi display', 'Floral table arrangements', 'Pink & gold balloons'],
      category: 'pan_india',
    },
    {
      key: 'janmashtami',
      name: 'Janmashtami – Krishna Janmotsav 🦚',
      country: 'IN',
      regions: ['all'],
      start: lunarDate('janmashtami', Y),
      end:   durationEnd(lunarDate('janmashtami', Y), 2),
      special_mode: 'satvik',
      theme: {
        primary: '#1565C0', accent: '#FFD700', bg: '#00001a',
        emoji: '🦚', banner: 'Jai Shri Krishna! Happy Janmashtami.',
        style: 'festive-blue-gold',
      },
      menu_tags: ['satvik', 'vrat', 'sweets', 'makhan', 'paneer', 'dahi'],
      suggested_items: ['Panchajiri', 'Gopalkala', 'Dahi Handi', 'Makhan Mishri', 'Panchamrit', 'Shrikhand', 'Makhane Ki Kheer'],
      offer_structure: { type: 'thali', label: 'Krishna Bhog Thali', value: 15, unit: 'percent', min_order: 250 },
      decor_tips: ['Peacock feather décor', 'Blue & yellow theme', 'Flute motifs', 'Dahi handi display'],
      category: 'pan_india',
    },
    {
      key: 'chhath_puja',
      name: 'Chhath Puja – Sun Festival 🌅',
      country: 'IN',
      regions: ['BR', 'JH', 'UP', 'DL', 'WB'],
      start: lunarDate('chhath_puja', Y),
      end:   durationEnd(lunarDate('chhath_puja', Y), 4),
      special_mode: 'satvik',
      theme: {
        primary: '#E65100', accent: '#FFD600', bg: '#1a0800',
        emoji: '🌅', banner: 'Jai Chhathi Maiya! Happy Chhath Puja.',
        style: 'festive-orange',
      },
      menu_tags: ['vrat', 'satvik', 'thekua', 'bihari', 'sweets'],
      suggested_items: ['Thekua', 'Kheer', 'Puri', 'Kaddu Ki Sabzi', 'Rice Kheer', 'Sugarcane Juice', 'Ganne Ki Rasam'],
      offer_structure: { type: 'thali', label: 'Chhath Puja Prasad Thali', value: 15, unit: 'percent', min_order: 200 },
      decor_tips: ['Sunrise/sunset motif', 'Orange & yellow diyas', 'Bamboo baskets décor'],
      category: 'regional',
    },
    {
      key: 'karva_chauth',
      name: 'Karva Chauth 🌕',
      country: 'IN',
      regions: ['PB', 'HR', 'UP', 'RJ', 'DL', 'MP'],
      start: lunarDate('karva_chauth', Y),
      end:   lunarDate('karva_chauth', Y),
      special_mode: null,
      theme: {
        primary: '#880E4F', accent: '#FFD700', bg: '#1a0010',
        emoji: '🌕', banner: 'Happy Karva Chauth! The festival of love.',
        style: 'festive-pink-gold',
      },
      menu_tags: ['sweets', 'sargi', 'mithai', 'beverages', 'dry_fruits'],
      suggested_items: ['Sargi Thali', 'Pheni', 'Mathri', 'Badam Halwa', 'Mewa Mix', 'Fruit Bowl', 'Special Dinner Thali'],
      offer_structure: { type: 'combo', label: 'Karva Chauth Celebration Dinner', value: 20, unit: 'percent', min_order: 400 },
      decor_tips: ['Full moon table centrepiece', 'Red & gold drapes', 'Earthen karwa display', 'Rose petals'],
      category: 'regional',
    },
    {
      key: 'teej',
      name: 'Hariyali Teej 🌿',
      country: 'IN',
      regions: ['RJ', 'UP', 'HR', 'PB', 'DL', 'MP'],
      start: lunarDate('teej', Y),
      end:   durationEnd(lunarDate('teej', Y), 2),
      special_mode: null,
      theme: {
        primary: '#2E7D32', accent: '#E91E63', bg: '#001500',
        emoji: '🌿', banner: 'Happy Teej! Blessings for a happy married life.',
        style: 'festive-green',
      },
      menu_tags: ['sweets', 'ghevar', 'satvik', 'green'],
      suggested_items: ['Ghevar', 'Malpua', 'Gujiya', 'Jalebi', 'Meetha Pua', 'Hara Bhara Kabab', 'Palak Paneer'],
      offer_structure: { type: 'combo', label: 'Teej Special Mithai Box', value: 12, unit: 'percent', min_order: 250 },
      decor_tips: ['Mehendi display', 'Green & pink drapes', 'Swing motif', 'Peacock décor'],
      category: 'regional',
    },
    {
      key: 'buddha_purnima',
      name: 'Buddha Purnima 🪷',
      country: 'IN',
      regions: ['all'],
      start: lunarDate('buddha_purnima', Y),
      end:   durationEnd(lunarDate('buddha_purnima', Y), 1),
      special_mode: 'satvik',
      theme: {
        primary: '#FF8F00', accent: '#FFFFFF', bg: '#0a0800',
        emoji: '🪷', banner: 'Buddha Purnima – Peace, Compassion & Wisdom.',
        style: 'festive-golden',
      },
      menu_tags: ['veg', 'satvik', 'khichdi', 'sweets', 'simple'],
      suggested_items: ['Kheer', 'Khichdi', 'Lotus Root Salad', 'Fruit Platter', 'Herbal Tea', 'Simple Thali'],
      offer_structure: { type: 'discount', label: 'Buddha Purnima Simple Meal', value: 10, unit: 'percent', min_order: 150 },
      decor_tips: ['Lotus flowers', 'Saffron cloth drapes', 'Buddha statue centrepiece', 'White & gold candles'],
      category: 'pan_india',
    },
    {
      key: 'guru_nanak_jayanti',
      name: 'Guru Nanak Jayanti – Gurpurab 🙏',
      country: 'IN',
      regions: ['PB', 'HR', 'HP', 'DL', 'JK', 'all'],
      start: lunarDate('guru_nanak_jayanti', Y),
      end:   durationEnd(lunarDate('guru_nanak_jayanti', Y), 2),
      special_mode: null,
      theme: {
        primary: '#F57F17', accent: '#1B5E20', bg: '#0a0800',
        emoji: '🙏', banner: 'Waheguru Ji Ka Khalsa! Happy Gurpurab.',
        style: 'festive-yellow',
      },
      menu_tags: ['langar', 'punjabi', 'satvik', 'karah_prashad'],
      suggested_items: ['Karah Prashad', 'Dal Makhani', 'Langar Daal', 'Roti', 'Kheer', 'Pinni', 'Lassi'],
      offer_structure: { type: 'thali', label: 'Gurpurab Langar Thali', value: 15, unit: 'percent', min_order: 200 },
      decor_tips: ['Sikh Khanda motif', 'Yellow & blue drapes', 'Marigold garlands', 'Diwan setting'],
      category: 'pan_india',
    },
    {
      key: 'milad_un_nabi',
      name: 'Milad-un-Nabi – Eid-e-Milad 🌙',
      country: 'IN',
      regions: ['all'],
      start: lunarDate('milad_un_nabi', Y),
      end:   durationEnd(lunarDate('milad_un_nabi', Y), 1),
      special_mode: null,
      theme: {
        primary: '#00695C', accent: '#FFD700', bg: '#001510',
        emoji: '🌙', banner: 'Eid Milad-un-Nabi Mubarak!',
        style: 'festive-green',
      },
      menu_tags: ['biryani', 'sweets', 'haleem', 'non_veg'],
      suggested_items: ['Mutton Biryani', 'Haleem', 'Sheer Khurma', 'Seviyan', 'Naan', 'Mutton Curry'],
      offer_structure: { type: 'combo', label: 'Eid-e-Milad Dawat', value: 15, unit: 'percent', min_order: 500 },
      decor_tips: ['Green & gold drapes', 'Crescent motifs', 'Arabic calligraphy'],
      category: 'pan_india',
    },
    {
      key: 'govardhan_puja',
      name: 'Govardhan Puja – Annakut 🏔️',
      country: 'IN',
      regions: ['UP', 'RJ', 'HR', 'DL', 'GJ', 'MH'],
      start: lunarDate('govardhan_puja', Y),
      end:   lunarDate('govardhan_puja', Y),
      special_mode: null,
      theme: {
        primary: '#FF8F00', accent: '#43A047', bg: '#0a0800',
        emoji: '🏔️', banner: 'Govardhan Puja ki Shubhkamnayein!',
        style: 'festive-orange',
      },
      menu_tags: ['annakut', 'satvik', 'prasad', 'sweets', 'veg'],
      suggested_items: ['Annakut Thali (56 items)', 'Kheer', 'Puri', 'Dal Baati', 'Halwa', 'Panchamrit'],
      offer_structure: { type: 'thali', label: 'Annakut Special Thali', value: 12, unit: 'percent', min_order: 300 },
      decor_tips: ['Govardhan hill motif with food', 'Flowers & diyas', 'Gold & orange theme'],
      category: 'regional',
    },
    {
      key: 'bhai_dooj',
      name: 'Bhai Dooj – Bhai Tika 💫',
      country: 'IN',
      regions: ['UP', 'DL', 'HR', 'PB', 'MH', 'WB'],
      start: lunarDate('bhai_dooj', Y),
      end:   lunarDate('bhai_dooj', Y),
      special_mode: null,
      theme: {
        primary: '#E91E63', accent: '#FF8F00', bg: '#1a0010',
        emoji: '💫', banner: 'Happy Bhai Dooj! Celebrate the sibling bond.',
        style: 'festive-pink',
      },
      menu_tags: ['sweets', 'mithai', 'snacks', 'family'],
      suggested_items: ['Mathura Peda', 'Kaju Burfi', 'Soan Papdi', 'Gujiya', 'Namkeen', 'Sweet Box'],
      offer_structure: { type: 'bundle', label: 'Bhai Dooj Sweet Combo', value: 12, unit: 'percent', min_order: 250 },
      decor_tips: ['Tika plate decorations', 'Gold & red theme', 'Floral arrangements'],
      category: 'regional',
    },

    // ─── NAVRATRI CHAITRA (Spring) ────────────────────────────────
    {
      key: 'navratri_chaitra',
      name: 'Chaitra Navratri – Spring Navratri 🌸',
      country: 'IN',
      regions: ['all'],
      start: lunarDate('navratri_chaitra', Y),
      end:   durationEnd(lunarDate('navratri_chaitra', Y), 9),
      special_mode: 'satvik',
      theme: {
        primary: '#AB47BC', accent: '#FF8F00', bg: '#1a0020',
        emoji: '🌸', banner: 'Jai Mata Di! Chaitra Navratri Greetings.',
        style: 'festive-purple',
      },
      menu_tags: ['vrat', 'satvik', 'no_onion_garlic', 'fasting'],
      suggested_items: ['Sabudana Khichdi', 'Kuttu Puri', 'Aloo Ki Subzi', 'Singhara Halwa', 'Makhana Kheer', 'Rajgira Paratha'],
      offer_structure: { type: 'thali', label: 'Navratri Vrat Thali', value: 12, unit: 'percent', min_order: 200 },
      decor_tips: ['Nine colors décor (one per day)', 'Marigold garlands', 'Devi images'],
      category: 'pan_india',
    },

    // ─── SOUTH INDIA ──────────────────────────────────────────────
    {
      key: 'onam',
      name: 'Onam – Harvest Festival 🌸',
      country: 'IN',
      regions: ['KL'],
      start: lunarDate('onam', Y),
      end:   durationEnd(lunarDate('onam', Y), 10),
      special_mode: 'sadhya',
      theme: {
        primary: '#F57F17', accent: '#2E7D32', bg: '#001500',
        emoji: '🌸', banner: 'Onam Ashamsakal! Onasadhya thayar.',
        style: 'festive-golden',
      },
      menu_tags: ['sadhya', 'kerala', 'banana_leaf', 'vegetarian'],
      suggested_items: ['Avial', 'Olan', 'Thoran', 'Erissery', 'Sambar', 'Rasam', 'Payasam', 'Pappadam', 'Pickle', 'Banana Chips', 'Pachadi', 'Kalan'],
      offer_structure: { type: 'sadhya_meal', label: 'Onam Sadhya Thali (26 dishes)', value: 10, unit: 'percent', min_order: 400 },
      decor_tips: ['Pookalam (flower rangoli)', 'Banana leaves as placemats', 'Yellow & green drapes', 'Traditional Kerala lamps (nilavilakku)'],
      category: 'state_specific',
    },
    {
      key: 'pongal',
      name: 'Thai Pongal – Harvest 🌾',
      country: 'IN',
      regions: ['TN'],
      start: d(Y, 1, 14),
      end:   d(Y, 1, 17),
      special_mode: 'pongal_special',
      theme: {
        primary: '#F9A825', accent: '#E65100', bg: '#1a0e00',
        emoji: '🌾', banner: 'Pongal O Pongal! Iniya Thai Pongal!',
        style: 'festive-yellow',
      },
      menu_tags: ['pongal', 'tamil', 'rice', 'jaggery'],
      suggested_items: ['Ven Pongal', 'Sakkarai Pongal', 'Medu Vada', 'Coconut Chutney', 'Sambar', 'Kozhukattai', 'Adhirasam', 'Murukku'],
      offer_structure: { type: 'thali', label: 'Pongal Special Meal', value: 15, unit: 'percent', min_order: 250 },
      decor_tips: ['Sugarcane décor', 'Clay pot Pongal display', 'Kolam at entrance', 'Banana bunches'],
      category: 'state_specific',
    },
    {
      key: 'vishu',
      name: 'Vishu – Kerala New Year ✨',
      country: 'IN',
      regions: ['KL'],
      start: d(Y, 4, 14),
      end:   d(Y, 4, 15),
      special_mode: 'sadhya',
      theme: {
        primary: '#F57F17', accent: '#FFD600', bg: '#1a1000',
        emoji: '✨', banner: 'Vishu Ashamsakal! Kanikkonna pookkal!',
        style: 'festive-golden',
      },
      menu_tags: ['kerala', 'sadhya', 'banana_leaf'],
      suggested_items: ['Vishu Kanji', 'Avial', 'Thoran', 'Erissery', 'Payasam', 'Papadom', 'Mango Pickle'],
      offer_structure: { type: 'sadhya_meal', label: 'Vishu Sadhya', value: 10, unit: 'percent', min_order: 350 },
      decor_tips: ['Kani display (fruits, gold, flowers)', 'Kanikkonna garlands', 'Banana leaves'],
      category: 'state_specific',
    },

    {
      key: 'ugadi',
      name: 'Ugadi – Telugu & Kannada New Year 🌿',
      country: 'IN',
      regions: ['AP', 'TS', 'KA'],
      start: lunarDate('ugadi_exact', Y),
      end:   durationEnd(lunarDate('ugadi_exact', Y), 2),
      special_mode: null,
      theme: {
        primary: '#558B2F', accent: '#FFD600', bg: '#0a1500',
        emoji: '🌿', banner: 'Ugadi Subhakankshalu! Iniya Ugadi Nal Vazhthukkal!',
        style: 'festive-green',
      },
      menu_tags: ['andhra', 'telangana', 'karnataka', 'tamarind', 'jaggery'],
      suggested_items: ['Ugadi Pachadi', 'Pulihora', 'Bobbatlu', 'Payasam', 'Pesarattu', 'Gongura Chutney', 'Holige'],
      offer_structure: { type: 'discount', label: 'Ugadi Special Combo', value: 12, unit: 'percent', min_order: 300 },
      decor_tips: ['Mango leaf torans', 'Neem flowers', 'Yellow & green decorations', 'Rangoli at entrance'],
      category: 'state_specific',
    },
    {
      key: 'gudi_padwa',
      name: 'Gudi Padwa – Maharashtrian New Year 🎏',
      country: 'IN',
      regions: ['MH', 'GJ'],
      start: lunarDate('gudi_padwa', Y),
      end:   durationEnd(lunarDate('gudi_padwa', Y), 1),
      special_mode: null,
      theme: {
        primary: '#E65100', accent: '#FFD600', bg: '#1a0800',
        emoji: '🎏', banner: 'Gudi Padwa chya Shubhechha!',
        style: 'festive-orange',
      },
      menu_tags: ['maharashtrian', 'puran_poli', 'sweets', 'shrikhand'],
      suggested_items: ['Puran Poli', 'Shrikhand', 'Aamras', 'Srikhand Puri', 'Batata Bhaji', 'Modak', 'Sunth Pak'],
      offer_structure: { type: 'thali', label: 'Gudi Padwa Special Thali', value: 12, unit: 'percent', min_order: 300 },
      decor_tips: ['Gudi (bamboo + cloth flag) display', 'Marigold garlands', 'Kolam at entrance'],
      category: 'state_specific',
    },
    {
      key: 'bihu',
      name: 'Bihu – Assamese New Year 🥁',
      country: 'IN',
      regions: ['AS', 'AR', 'NL', 'MN', 'ML', 'MZ'],
      start: lunarDate('bihu_bohag', Y),
      end:   durationEnd(lunarDate('bihu_bohag', Y), 7),
      special_mode: null,
      theme: {
        primary: '#E65100', accent: '#43A047', bg: '#0a0800',
        emoji: '🥁', banner: 'Rongali Bihu! Happy Assamese New Year.',
        style: 'festive-orange',
      },
      menu_tags: ['assamese', 'rice', 'fish', 'pitha', 'northeast'],
      suggested_items: ['Pitha', 'Laru', 'Fish Curry', 'Duck Meat', 'Masor Tenga', 'Rice Beer', 'Joha Rice'],
      offer_structure: { type: 'combo', label: 'Bihu Special Meal', value: 15, unit: 'percent', min_order: 300 },
      decor_tips: ['Bihu dance motifs', 'Bamboo décor', 'Gamosa (red-white cloth) display', 'Traditional drum'],
      category: 'state_specific',
    },
    {
      key: 'new_year_in',
      name: "New Year's Day 🎆",
      country: 'IN',
      regions: ['all'],
      start: d(Y, 1, 1),
      end:   d(Y, 1, 1),
      special_mode: null,
      theme: {
        primary: '#1A237E', accent: '#FFD700', bg: '#000010',
        emoji: '🎆', banner: `Happy New Year ${Y}! नया साल मुबारक!`,
        style: 'festive-midnight',
      },
      menu_tags: ['party', 'cocktails', 'mocktails', 'snacks', 'desserts'],
      suggested_items: ['Champagne Mocktail', 'Cheese Platter', 'Paneer Tikka', 'Chocolate Cake', 'Mini Sliders', 'Fruit Punch'],
      offer_structure: { type: 'bundle', label: 'New Year Celebration Package', value: 20, unit: 'percent', min_order: 500 },
      decor_tips: ['Countdown banner', 'Balloon arch', 'Silver & gold table settings', 'Confetti cannons'],
      category: 'pan_india',
    },

    // ─── NORTH & WEST INDIA ───────────────────────────────────────
    {
      key: 'lohri',
      name: 'Lohri – Punjabi Harvest Fire 🔥',
      country: 'IN',
      regions: ['PB', 'HR', 'HP', 'JK', 'DL'],
      start: d(Y, 1, 13),
      end:   d(Y, 1, 14),
      special_mode: 'lohri_special',
      theme: {
        primary: '#E53935', accent: '#FF8F00', bg: '#1a0500',
        emoji: '🔥', banner: 'Sunder Mundariye! Happy Lohri!',
        style: 'festive-fire',
      },
      menu_tags: ['punjabi', 'sarson', 'makki', 'butter', 'rewari', 'til'],
      suggested_items: ['Sarson Da Saag', 'Makki Di Roti', 'White Butter', 'Gur Di Kheer', 'Til Ladoo', 'Rewari', 'Peanut Chikki', 'Lassi', 'Pinni'],
      offer_structure: { type: 'combo', label: 'Lohri Dhaba Special', value: 20, unit: 'percent', min_order: 400 },
      decor_tips: ['Bonfire motif, phulkari embroidery', 'Earthen diyas', 'Yellow & orange mustard flowers', 'Jute table runners'],
      category: 'state_specific',
    },
    {
      key: 'baisakhi',
      name: 'Baisakhi – Punjab Harvest 🌾',
      country: 'IN',
      regions: ['PB', 'HR', 'HP', 'DL'],
      start: d(Y, 4, 13),
      end:   d(Y, 4, 14),
      special_mode: 'baisakhi_special',
      theme: {
        primary: '#F57F17', accent: '#1B5E20', bg: '#0a1000',
        emoji: '🌾', banner: 'Wahe Guru! Happy Baisakhi!',
        style: 'festive-yellow',
      },
      menu_tags: ['punjabi', 'amritsari', 'lassi', 'butter', 'sarson'],
      suggested_items: ['Amritsari Chole', 'Makki Roti', 'Sarson Saag', 'Mango Lassi', 'Pinni', 'Gajrela', 'Karah Prashad', 'Langar Daal'],
      offer_structure: { type: 'thali', label: 'Baisakhi Grand Thali', value: 15, unit: 'percent', min_order: 350 },
      decor_tips: ['Bhangra dancer cutouts', 'Wheat stalks bouquets', 'Phulkari banner', 'Yellow & green balloons'],
      category: 'state_specific',
    },
    {
      key: 'ganesh_chaturthi',
      name: 'Ganesh Chaturthi 🐘',
      country: 'IN',
      regions: ['MH', 'GJ', 'KA', 'AP', 'TS'],
      start: lunarDate('ganesh_chaturthi', Y),
      end:   durationEnd(lunarDate('ganesh_chaturthi', Y), 10),
      special_mode: null,
      theme: {
        primary: '#FF8F00', accent: '#E53935', bg: '#1a0a00',
        emoji: '🐘', banner: 'Ganpati Bappa Morya! 🐘',
        style: 'festive-orange',
      },
      menu_tags: ['modak', 'sweets', 'maharashtrian', 'veg'],
      suggested_items: ['Ukadiche Modak', 'Fried Modak', 'Puran Poli', 'Karanji', 'Kothimbir Vadi', 'Shrikhand', 'Batata Vada', 'Coconut Laddoo'],
      offer_structure: { type: 'combo', label: 'Modak Combo Platter', value: 15, unit: 'percent', min_order: 300 },
      decor_tips: ['Ganesh idol centrepiece', 'Marigold garlands', 'Orange & red drapes', 'Banana leaf décor'],
      category: 'state_specific',
    },
    {
      key: 'durga_puja',
      name: 'Durga Puja – Mahasaptami to Vijayadashami 🌺',
      country: 'IN',
      regions: ['WB', 'AS', 'OR', 'TRP'],
      start: lunarDate('durga_puja', Y),
      end:   durationEnd(lunarDate('durga_puja', Y), 5),
      special_mode: null,
      theme: {
        primary: '#C62828', accent: '#FF8F00', bg: '#1a0000',
        emoji: '🌺', banner: 'Subho Bijoya! Durga Puja Greetings.',
        style: 'festive-red',
      },
      menu_tags: ['bengali', 'mishti', 'fish', 'mutton'],
      suggested_items: ['Kosha Mangsho', 'Luchi', 'Mishti Doi', 'Rasgolla', 'Prawn Malai Curry', 'Bhetki Fish Fry', 'Sandesh', 'Chelo Kebab'],
      offer_structure: { type: 'thali', label: 'Pujo Special Bhoj', value: 18, unit: 'percent', min_order: 500 },
      decor_tips: ['Dhunuchi (incense burner)', 'Red & white flowers', 'Bengal cotton saree motifs', 'Dhaak drum display'],
      category: 'state_specific',
    },

    // ─── AUSTRALIA ────────────────────────────────────────────────
    {
      key: 'au_christmas',
      name: 'Christmas – Summer Edition 🎄☀️',
      country: 'AU',
      regions: ['all'],
      start: d(Y, 12, 20),
      end:   d(Y, 12, 27),
      special_mode: 'summer_christmas',
      theme: {
        primary: '#C62828', accent: '#F9A825', bg: '#001400',
        emoji: '🎄', banner: 'Merry Christmas! Summer BBQ special.',
        style: 'festive-red-green',
      },
      menu_tags: ['bbq', 'seafood', 'cold_drinks', 'pavlova', 'roast'],
      suggested_items: ['BBQ Prawns', 'Grilled Barramundi', 'Pavlova', 'Cold Turkey Salad', 'Trifle', 'Mango Sorbet', 'Sparkling Lemonade', 'Summer Sangria'],
      offer_structure: { type: 'bundle', label: 'Christmas BBQ Feast', value: 20, unit: 'percent', min_order: 80 },
      decor_tips: ['Outdoor summer vibes', 'Fairy lights on veranda', 'Beach-themed Christmas', 'Tropical flowers'],
      category: 'australia',
    },
    {
      key: 'au_australia_day',
      name: "Australia Day 🇦🇺",
      country: 'AU',
      regions: ['all'],
      start: d(Y, 1, 26),
      end:   d(Y, 1, 27),
      special_mode: null,
      theme: {
        primary: '#003087', accent: '#FFD700', bg: '#000820',
        emoji: '🇦🇺', banner: "G'day! Celebrate Australia Day.",
        style: 'festive-blue-gold',
      },
      menu_tags: ['bbq', 'lamb', 'beef', 'cold_drinks', 'pies'],
      suggested_items: ['Lamb Chops', 'Beef Burger', 'Sausage Sizzle', 'Tim Tam Slice', 'Meat Pie', 'Vegemite Toast', 'XXXX Gold Beer Battered Fish', 'Lamington'],
      offer_structure: { type: 'discount', label: "Aussie BBQ Special", value: 15, unit: 'percent', min_order: 60 },
      decor_tips: ['Australian flag bunting', 'Green & gold table covers', 'Outdoor BBQ setup'],
      category: 'australia',
    },
    {
      key: 'au_easter',
      name: 'Easter Long Weekend 🐣',
      country: 'AU',
      regions: ['all'],
      start: d(Y, 3, 29), // approximate, varies
      end:   d(Y, 4, 1),
      special_mode: null,
      theme: {
        primary: '#7B1FA2', accent: '#F9A825', bg: '#0d0020',
        emoji: '🐣', banner: 'Happy Easter! Hot cross buns & more.',
        style: 'festive-purple',
      },
      menu_tags: ['hot_cross_buns', 'chocolate', 'seafood', 'lamb'],
      suggested_items: ['Hot Cross Buns', 'Chocolate Fondant', 'Grilled Snapper', 'Roast Lamb', 'Simnel Cake', 'Easter Egg Pancakes', 'Seafood Platter'],
      offer_structure: { type: 'combo', label: 'Easter Brunch Special', value: 18, unit: 'percent', min_order: 70 },
      decor_tips: ['Pastel Easter eggs', 'Bunny figurines', 'Spring flower bouquets', 'Purple & yellow colour scheme'],
      category: 'australia',
    },
    {
      key: 'au_melbourne_cup',
      name: 'Melbourne Cup – Race That Stops a Nation 🏇',
      country: 'AU',
      regions: ['VIC', 'all'],
      start: d(Y, 11, 4), // first Tuesday November approx
      end:   d(Y, 11, 4),
      special_mode: null,
      theme: {
        primary: '#880E4F', accent: '#F9A825', bg: '#1a0010',
        emoji: '🏇', banner: "It's race day! Melbourne Cup specials.",
        style: 'festive-pink-gold',
      },
      menu_tags: ['champagne_food', 'finger_food', 'afternoon_tea', 'canapés'],
      suggested_items: ['Smoked Salmon Blinis', 'Prawn Cocktail', 'Champagne Chicken', 'Strawberry Tart', 'Cheese Platter', 'Devilled Eggs', 'Cucumber Sandwiches'],
      offer_structure: { type: 'bundle', label: 'Cup Day Champagne Package', value: 15, unit: 'percent', min_order: 100 },
      decor_tips: ['Racing silks colour scheme', 'Fascinator hat display', 'Gold & rose gold décor'],
      category: 'australia',
    },
    {
      key: 'au_lunar_new_year',
      name: 'Lunar New Year 🐲',
      country: 'AU',
      regions: ['NSW', 'VIC', 'all'],
      start: lunarDate('chinese_new_year', Y),
      end:   durationEnd(lunarDate('chinese_new_year', Y), 3),
      special_mode: null,
      theme: {
        primary: '#C62828', accent: '#FFD700', bg: '#1a0000',
        emoji: '🐲', banner: 'Gong Xi Fa Cai! Chúc Mừng Năm Mới!',
        style: 'festive-red-gold',
      },
      menu_tags: ['dumplings', 'noodles', 'asian', 'dim_sum', 'lucky_foods'],
      suggested_items: ['Dim Sum Basket', 'Long Life Noodles', 'Peking Duck', 'Spring Rolls', 'Char Siu Bao', 'Mango Pudding', 'Pineapple Cake', 'Longevity Buns'],
      offer_structure: { type: 'combo', label: 'Lucky Feast Combo', value: 12, unit: 'percent', min_order: 80 },
      decor_tips: ['Red lanterns', 'Gold ingots', 'Lucky red envelopes', 'Dragon motifs'],
      category: 'australia',
    },

    {
      key: 'au_anzac_day',
      name: 'ANZAC Day 🌺',
      country: 'AU',
      regions: ['all'],
      start: d(Y, 4, 25),
      end:   d(Y, 4, 25),
      special_mode: null,
      theme: {
        primary: '#1B2A4A', accent: '#D4AF37', bg: '#000510',
        emoji: '🌺', banner: 'Lest We Forget. ANZAC Day.',
        style: 'festive-navy-gold',
      },
      menu_tags: ['anzac_biscuits', 'classic', 'pub', 'lamb', 'beverages'],
      suggested_items: ['ANZAC Biscuits', 'Lamb Shanks', 'Pub Burger', 'Meat Pie', 'Pea & Ham Soup', 'Sausage Rolls', 'Victoria Sponge'],
      offer_structure: { type: 'discount', label: 'ANZAC Day Special', value: 10, unit: 'percent', min_order: 50 },
      decor_tips: ['Red poppies display', 'Navy & gold table settings', 'Australian & NZ flags'],
      category: 'australia',
    },
    {
      key: 'au_good_friday',
      name: 'Good Friday 🙏',
      country: 'AU',
      regions: ['all'],
      start: lunarDate('easter', Y),
      end:   lunarDate('easter', Y),
      special_mode: null,
      theme: {
        primary: '#6A1B9A', accent: '#F9A825', bg: '#0d0020',
        emoji: '🙏', banner: 'Good Friday – Seafood & Reflection.',
        style: 'festive-purple',
      },
      menu_tags: ['seafood', 'hot_cross_buns', 'fish', 'no_meat'],
      suggested_items: ['Fish & Chips', 'Grilled Snapper', 'Hot Cross Buns', 'Prawn Salad', 'Smoked Salmon', 'Seafood Chowder'],
      offer_structure: { type: 'combo', label: 'Good Friday Seafood Special', value: 15, unit: 'percent', min_order: 60 },
      decor_tips: ['Purple & gold', 'Lilies centrepiece', 'Simple elegant table settings'],
      category: 'australia',
    },
    {
      key: 'au_boxing_day',
      name: 'Boxing Day 🎁',
      country: 'AU',
      regions: ['all'],
      start: d(Y, 12, 26),
      end:   d(Y, 12, 27),
      special_mode: null,
      theme: {
        primary: '#1565C0', accent: '#E53935', bg: '#000a20',
        emoji: '🎁', banner: 'Happy Boxing Day! Big sales & summer feasting.',
        style: 'festive-blue-red',
      },
      menu_tags: ['leftovers', 'bbq', 'summer', 'cold_meats', 'pavlova'],
      suggested_items: ['Cold Turkey Platter', 'Ham on Bone', 'Pavlova', 'Summer Salad', 'Seafood BBQ', 'Leftover Toasties', 'Mango Sorbet'],
      offer_structure: { type: 'discount', label: 'Boxing Day Summer Feast', value: 26, unit: 'percent', min_order: 60 },
      decor_tips: ['Summer BBQ setup', 'Post-Christmas relaxed style', 'Australian summer vibes'],
      category: 'australia',
    },
    {
      key: 'au_queens_birthday',
      name: "King's Birthday Long Weekend 👑",
      country: 'AU',
      regions: ['VIC', 'NSW', 'ACT', 'SA', 'TAS', 'QLD'],
      start: d(Y, 6, 9),  // 2nd Monday June approx (VIC/NSW)
      end:   d(Y, 6, 10),
      special_mode: null,
      theme: {
        primary: '#1A237E', accent: '#FFD700', bg: '#000010',
        emoji: '👑', banner: "God Save the King! Long Weekend Celebrations.",
        style: 'festive-royal',
      },
      menu_tags: ['afternoon_tea', 'english', 'scones', 'pub', 'lamb'],
      suggested_items: ['Scones with Jam & Cream', 'Finger Sandwiches', 'Lamington', 'Pork Ribs', 'Sunday Roast', 'Pavlova', 'Champagne'],
      offer_structure: { type: 'bundle', label: "King's Birthday Long Weekend Menu", value: 15, unit: 'percent', min_order: 70 },
      decor_tips: ['Royal blue & gold', 'Crown motifs', 'Union Jack accents', 'Elegant afternoon tea setup'],
      category: 'australia',
    },
    {
      key: 'au_labour_day',
      name: 'Labour Day Long Weekend 🛠️',
      country: 'AU',
      regions: ['all'],
      start: d(Y, 3, 10), // 2nd Mon March approx (varies by state)
      end:   d(Y, 3, 11),
      special_mode: null,
      theme: {
        primary: '#D32F2F', accent: '#FFD700', bg: '#1a0000',
        emoji: '🛠️', banner: 'Happy Labour Day! Enjoy the long weekend.',
        style: 'festive-red',
      },
      menu_tags: ['bbq', 'pub', 'casual', 'burgers', 'cold_drinks'],
      suggested_items: ['Sausage Sizzle', 'Beef Burger', 'Chicken Wings', 'Coleslaw', 'Potato Wedges', 'Cold Beer Battered Fish'],
      offer_structure: { type: 'discount', label: 'Labour Day BBQ Special', value: 15, unit: 'percent', min_order: 50 },
      decor_tips: ['Casual outdoor BBQ setup', 'Red & gold', 'Workers & community motifs'],
      category: 'australia',
    },
    {
      key: 'au_mardi_gras',
      name: 'Sydney Mardi Gras 🌈',
      country: 'AU',
      regions: ['NSW'],
      start: d(Y, 3, 1),  // 1st Saturday of March approx
      end:   d(Y, 3, 2),
      special_mode: null,
      theme: {
        primary: '#9C27B0', accent: '#FF4081', bg: '#1a0020',
        emoji: '🌈', banner: 'Happy Mardi Gras! Celebrate diversity.',
        style: 'festive-rainbow',
      },
      menu_tags: ['cocktails', 'party_food', 'finger_food', 'canapés', 'inclusive'],
      suggested_items: ['Rainbow Macarons', 'Canapé Platter', 'Champagne Cocktails', 'Mini Burgers', 'Sushi Platter', 'Fruit Skewers'],
      offer_structure: { type: 'bundle', label: 'Mardi Gras Party Package', value: 20, unit: 'percent', min_order: 80 },
      decor_tips: ['Rainbow flags', 'Glitter & sparkle décor', 'Purple, pink & blue theme'],
      category: 'australia',
    },
    {
      key: 'au_afl_grand_final',
      name: 'AFL Grand Final 🏈',
      country: 'AU',
      regions: ['VIC', 'QLD', 'WA', 'SA', 'NSW'],
      start: d(Y, 9, 27), // last Saturday September approx
      end:   d(Y, 9, 27),
      special_mode: null,
      theme: {
        primary: '#1B5E20', accent: '#FFD600', bg: '#000800',
        emoji: '🏈', banner: 'AFL Grand Final Day! Footy, Food & Friends.',
        style: 'festive-green-gold',
      },
      menu_tags: ['pub', 'pies', 'bbq', 'wings', 'cold_drinks', 'party'],
      suggested_items: ['Meat Pies', 'Dim Sims', 'Party Pies', 'Sausage Rolls', 'Chicken Wings', 'Loaded Nachos', 'Beer Battered Chips'],
      offer_structure: { type: 'bundle', label: 'Grand Final Game Day Package', value: 20, unit: 'percent', min_order: 80 },
      decor_tips: ['Team colors themed setup', 'AFL themed banners', 'Big screen viewing area'],
      category: 'australia',
    },
    {
      key: 'au_mothers_day',
      name: "Mother's Day 💐",
      country: 'AU',
      regions: ['all'],
      start: d(Y, 5, 11), // 2nd Sunday May approx
      end:   d(Y, 5, 11),
      special_mode: null,
      theme: {
        primary: '#E91E63', accent: '#FFFFFF', bg: '#1a0010',
        emoji: '💐', banner: "Happy Mother's Day! Treat Mum to something special.",
        style: 'festive-pink',
      },
      menu_tags: ['brunch', 'afternoon_tea', 'desserts', 'flowers', 'family'],
      suggested_items: ['High Tea Platter', 'Smashed Avo Brunch', 'Floral Macarons', 'Champagne', 'Eggs Benedict', 'Strawberry Pavlova', 'Crème Brûlée'],
      offer_structure: { type: 'bundle', label: "Mother's Day High Tea Package", value: 15, unit: 'percent', min_order: 80 },
      decor_tips: ['Fresh flowers centrepieces', 'Pink & white table linens', 'Elegant brunch setup'],
      category: 'australia',
    },
    {
      key: 'au_fathers_day',
      name: "Father's Day 🍺",
      country: 'AU',
      regions: ['all'],
      start: d(Y, 9, 7), // 1st Sunday September approx (AU)
      end:   d(Y, 9, 7),
      special_mode: null,
      theme: {
        primary: '#1565C0', accent: '#FF8F00', bg: '#000a20',
        emoji: '🍺', banner: "Happy Father's Day! For the best dads.",
        style: 'festive-blue',
      },
      menu_tags: ['bbq', 'steak', 'pub', 'burgers', 'cold_drinks'],
      suggested_items: ['Wagyu Steak', 'Beef Ribs', 'Loaded Burger', 'Beer Platter', 'Garlic Prawn', 'Sausage Sizzle', 'Cheese Board'],
      offer_structure: { type: 'combo', label: "Father's Day BBQ Feast", value: 15, unit: 'percent', min_order: 80 },
      decor_tips: ['Masculine colours navy/orange', 'BBQ setup', 'Sports-themed decor'],
      category: 'australia',
    },
    {
      key: 'au_new_year',
      name: "New Year's Eve & Day 🎆",
      country: 'AU',
      regions: ['all'],
      start: d(Y, 12, 31),
      end:   d(Y+1, 1, 1),
      special_mode: null,
      theme: {
        primary: '#1A237E', accent: '#FFD700', bg: '#000010',
        emoji: '🎆', banner: `Happy New Year ${Y+1}! Sydney Harbour Fireworks!`,
        style: 'festive-midnight',
      },
      menu_tags: ['party', 'cocktails', 'bbq', 'seafood', 'desserts'],
      suggested_items: ['Seafood Platter', 'Champagne', 'Canapé Platter', 'Pavlova', 'BBQ Prawns', 'Sushi', 'Midnight Cake'],
      offer_structure: { type: 'bundle', label: 'NYE Harbour Party Package', value: 25, unit: 'percent', min_order: 100 },
      decor_tips: ['Fireworks-themed décor', 'Silver & gold balloons', 'Countdown display', 'Outdoor harbour view setup'],
      category: 'australia',
    },
    {
      key: 'au_valentines',
      name: "Valentine's Day ❤️",
      country: 'AU',
      regions: ['all'],
      start: d(Y, 2, 14),
      end:   d(Y, 2, 14),
      special_mode: null,
      theme: {
        primary: '#C62828', accent: '#FF80AB', bg: '#1a0000',
        emoji: '❤️', banner: "Happy Valentine's Day! Dine with your love.",
        style: 'festive-red',
      },
      menu_tags: ['date_night', 'fine_dining', 'seafood', 'desserts', 'cocktails'],
      suggested_items: ['Oysters', 'Lobster Thermidor', 'Wagyu Steak', 'Chocolate Fondant', 'Rose Champagne', 'Crème Brûlée', 'Strawberry Tart'],
      offer_structure: { type: 'bundle', label: "Valentine's Degustation for Two", value: 20, unit: 'percent', min_order: 120 },
      decor_tips: ['Red roses centrepieces', 'Candlelit tables', 'Heart motifs', 'Rose petals floor path'],
      category: 'australia',
    },

  ];

  return festivals;
}

// Region code → state name map (India)
const INDIA_REGIONS = {
  AN: 'Andaman & Nicobar', AP: 'Andhra Pradesh', AR: 'Arunachal Pradesh',
  AS: 'Assam', BR: 'Bihar', CH: 'Chandigarh', CG: 'Chhattisgarh',
  DL: 'Delhi', DN: 'Dadra & Nagar Haveli', GA: 'Goa', GJ: 'Gujarat',
  HR: 'Haryana', HP: 'Himachal Pradesh', JK: 'Jammu & Kashmir',
  JH: 'Jharkhand', KA: 'Karnataka', KL: 'Kerala', LA: 'Ladakh',
  MP: 'Madhya Pradesh', MH: 'Maharashtra', MN: 'Manipur', ML: 'Meghalaya',
  MZ: 'Mizoram', NL: 'Nagaland', OR: 'Odisha', PY: 'Puducherry',
  PB: 'Punjab', RJ: 'Rajasthan', SK: 'Sikkim', TN: 'Tamil Nadu',
  TS: 'Telangana', TRP: 'Tripura', UP: 'Uttar Pradesh', UK: 'Uttarakhand',
  WB: 'West Bengal',
};

// Australia state codes
const AU_REGIONS = {
  NSW: 'New South Wales', VIC: 'Victoria', QLD: 'Queensland',
  WA: 'Western Australia', SA: 'South Australia', TAS: 'Tasmania',
  ACT: 'Australian Capital Territory', NT: 'Northern Territory',
};

module.exports = { generateCalendar, INDIA_REGIONS, AU_REGIONS };
